language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- RAILS_ENV=test bundle exec rake db:test:prepare --trace
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: iq76lN2gQqJhZ1C8jMmy+g5l4HnAiB+3M+Yx9z6JhiPlGUrm7A4o5G/7cfJIp+HgaSk5qOe/+cmgKa8rO+9JUjiCjdHyapocD1UKFrfgBSFUfAWtEalOfTNyY5UI7u2iFNrLnFNL8+dlmILJSJdJAfB+cLDXplgbn9CQYUC2Oz7uOiSTluoZBU9/sjAhF2p+urNYF7dzK3FA6ZyNSMWmqy73IjPRvcqofjDd+3fFQhj+44w3Qu81KOaYZC0fuqbybiubucGEd9GZEF/m+qDW3o5QdkBxWJsmaYB4DF5YtiBzZ5w9LJUY54IXmNSTnCS/xdjWrA8lYGdk47UhjeYJk7jUBaDpdanlk31HROZiPI/zurbTwn6I1m8g555N2e8GzVgjRP4yA368yIwK3utoYPNux52rcEYCiKB/pr3NnXI8EmYWfRjmXsZFvo8dOjbhHUl8dSLA5Q1EWOJI/Pv3qOG8KQXyELFaELi7XDRK88pwCSBA7E886nkv/gAl6MB3P09YNPNN9RbPGNQfPYnsFaEfZTok8NamREQrmz7E7FmP/eOR6v+d7cwo9YwLA40n/62XUJA16ZH79kQz1XVcEpV/GmLDMGUTajn1TdOQV8ENW2H9napn5ThZbs15Ix2e0/Nc7OHKn0yOU/z2wFnZTG337BRqom/zAzWJmhj9l3s=
  app: whether-sweater-23110
  run: rails db:migrate
  on:
    repo: kaiheiongaku/whether_sweater
    branch: main
  skip_cleanup: 'true'
